### ISSUE TITLE
[Not related to excatly this] - pc-compat for BD?

### ISSUE THREAD

**Issue by Dschogo** [Juby210/bdCompat#32]
Hey i've seen ur Powercord Loader plugin but it seems to be very out of date and im not entirely sure if its funciton as an compat. 

So im basically searching the excatly opposite of this plugin. A pc-compat for BD

Got a few questions:

Is it possible to create a pc-compat for Better Discord?
If is there already one? (searched but nothing found, maybe you know more)
Possible to (easily) write one? 

Thx in advance

**Comment by Juby210** [comment]
Hi!
1. I am not really sure, because I last used BD years ago, and it was possible to create "pc-compat" for BD then, it might be not possible right now due to context changes and stuff.
2. Nope
3. It might be hard to do that as you have to reimplement powercord components and APIs (and powercord has much more APIs/components than BD), as well you have to implement jsx compiler etc..

**Comment by Dschogo** [comment]
Hmm okay, so im better off with just using it the other way round. Thx for the quick and precise answer :D
